services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wildberries_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - l0task-app
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - l0task-app
    restart: unless-stopped

  nats-streaming:
    command:
      - "--cluster_id"
      - app-cluster
    image: library/nats-streaming:latest
    restart: always
    container_name: nats-streaming
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - nats-streaming:/var/lib/nats-streaming
    networks:
      - l0task-app

networks:
  l0task-app:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  nats-streaming: